package optimization;

import java.io.IOException;

//ensure this class is managed by spring.

public class Optimizer {
	
	//managed by spring
	Population population = new Population();

	public static void main (String[] args) throws IOException {
		long timeStart, timeEnd, timeDuration;
		boolean PopulationNotOld = true;
		boolean BestPersonNotOld = true;
		
		timeStart = System.currentTimeMillis();
		
		String pathIn = "C:\\Users\\Marcin\\Desktop\\Java\\Genetic2\\Indata.txt";
		String pathOut = "C:\\Users\\Marcin\\Desktop\\Java\\Genetic2\\Outdata.txt";
		
		// read the input data from text file generated by Excel file and initial creation of population and goal function calculations
		
		if (args.length > 1){
			pathIn = args[0];
			pathOut = args[1];
		} else {
			throw new IOException("\n------------\nThe program cannot run without input and output file path."
					+ "\nTry again with correct input and output file paths.\n------------"); 
		}
				 
		Input.readInput(pathIn);
		
		Optimizer optimizer = new Optimizer();

		optimizer.population.calculateScores();
		
		//perform loop of genetic operators on population and calculation of goal function till boundary limits of population age are met
		
		do{
			if (population.getAge() % 10 == 0) {
			System.out.println("Calculating generation number " + population.getAge() + ", Best score till now is: " + population.getBestPerson().getScore());
			}
			
			Genetic.Selection(optimizer.population);
			Genetic.Crossing(optimizer.population);
			Genetic.Mutation(optimizer.population);
			
			optimizer.population.calculateScores();
			
			PopulationNotOld = optimizer.population.getAge() < Input.getMaxNoGenerations();
			BestPersonNotOld = optimizer.population.getBestPerson().getAge() < Input.getBestPersonMaxAge();			
			
		} while (PopulationNotOld && BestPersonNotOld);
		
		timeEnd = System.currentTimeMillis();
		timeDuration = (timeEnd - timeStart);


		// generate output file with results of genetic optimization
		System.out.println("Genetic optimization is finished.\nResulted values of variables are:");
		for (int i = 0; i < Input.getNumberOfVariables(); i++) {
			System.out.println("Variable " + i + ": " + optimizer.population.getBestPerson().getVariable(i));
		}
		System.out.println("Score is: " + optimizer.population.getBestPerson().getScore());
		System.out.println("Time of calculation in milisec was: " + timeDuration);
		
		Input.reportStatus(pathOut, optimizer.population);

	
	}

}
